/* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_api_v2_core_base_pb = require('./envoy/api/v2/core/base_pb.js');
goog.object.extend(proto, envoy_api_v2_core_base_pb);
var envoy_api_v2_route_route_pb = require('./envoy/api/v2/route/route_pb.js');
goog.object.extend(proto, envoy_api_v2_route_route_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var validate_validate_pb = require('./validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
var gogoproto_gogo_pb = require('./gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route', null, global);
goog.exportSymbol('proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction', null, global);
goog.exportSymbol('proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration', null, global);
goog.exportSymbol('proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch', null, global);
goog.exportSymbol('proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster', null, global);
goog.exportSymbol('proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.displayName = 'proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.displayName = 'proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.repeatedFields_, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.oneofGroups_);
};
goog.inherits(proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.displayName = 'proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.repeatedFields_, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.oneofGroups_);
};
goog.inherits(proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.displayName = 'proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.displayName = 'proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.displayName = 'proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    routesList: jspb.Message.toObjectList(msg.getRoutesList(),
    proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration;
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route;
      reader.readMessage(value,proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.deserializeBinaryFromReader);
      msg.addRoutes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRoutesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Route routes = 2;
 * @return {!Array<!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route>}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.prototype.getRoutesList = function() {
  return /** @type{!Array<!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route, 2));
};


/** @param {!Array<!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route>} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.prototype.setRoutesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.prototype.addRoutes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration.prototype.clearRoutesList = function() {
  this.setRoutesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.toObject = function(includeInstance, msg) {
  var f, obj = {
    match: (f = msg.getMatch()) && proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.toObject(includeInstance, f),
    route: (f = msg.getRoute()) && proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route;
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch;
      reader.readMessage(value,proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.deserializeBinaryFromReader);
      msg.setMatch(value);
      break;
    case 2:
      var value = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction;
      reader.readMessage(value,proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.deserializeBinaryFromReader);
      msg.setRoute(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMatch();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.serializeBinaryToWriter
    );
  }
  f = message.getRoute();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.serializeBinaryToWriter
    );
  }
};


/**
 * optional RouteMatch match = 1;
 * @return {?proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.getMatch = function() {
  return /** @type{?proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch, 1));
};


/** @param {?proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch|undefined} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.setMatch = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.clearMatch = function() {
  this.setMatch(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.hasMatch = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional RouteAction route = 2;
 * @return {?proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.getRoute = function() {
  return /** @type{?proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction, 2));
};


/** @param {?proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction|undefined} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.setRoute = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.clearRoute = function() {
  this.setRoute(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.Route.prototype.hasRoute = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.repeatedFields_ = [4];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.MatchSpecifierCase = {
  MATCH_SPECIFIER_NOT_SET: 0,
  METHOD_NAME: 1,
  SERVICE_NAME: 2
};

/**
 * @return {proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.MatchSpecifierCase}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.getMatchSpecifierCase = function() {
  return /** @type {proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.MatchSpecifierCase} */(jspb.Message.computeOneofCase(this, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.toObject = function(includeInstance, msg) {
  var f, obj = {
    methodName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    serviceName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    invert: jspb.Message.getFieldWithDefault(msg, 3, false),
    headersList: jspb.Message.toObjectList(msg.getHeadersList(),
    envoy_api_v2_route_route_pb.HeaderMatcher.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch;
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMethodName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceName(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInvert(value);
      break;
    case 4:
      var value = new envoy_api_v2_route_route_pb.HeaderMatcher;
      reader.readMessage(value,envoy_api_v2_route_route_pb.HeaderMatcher.deserializeBinaryFromReader);
      msg.addHeaders(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getInvert();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getHeadersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      envoy_api_v2_route_route_pb.HeaderMatcher.serializeBinaryToWriter
    );
  }
};


/**
 * optional string method_name = 1;
 * @return {string}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.getMethodName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.setMethodName = function(value) {
  jspb.Message.setOneofField(this, 1, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.clearMethodName = function() {
  jspb.Message.setOneofField(this, 1, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.hasMethodName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string service_name = 2;
 * @return {string}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.getServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.setServiceName = function(value) {
  jspb.Message.setOneofField(this, 2, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.clearServiceName = function() {
  jspb.Message.setOneofField(this, 2, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.hasServiceName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool invert = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.getInvert = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.setInvert = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * repeated envoy.api.v2.route.HeaderMatcher headers = 4;
 * @return {!Array<!proto.envoy.api.v2.route.HeaderMatcher>}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.getHeadersList = function() {
  return /** @type{!Array<!proto.envoy.api.v2.route.HeaderMatcher>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_api_v2_route_route_pb.HeaderMatcher, 4));
};


/** @param {!Array<!proto.envoy.api.v2.route.HeaderMatcher>} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.setHeadersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.envoy.api.v2.route.HeaderMatcher=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.api.v2.route.HeaderMatcher}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.addHeaders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.envoy.api.v2.route.HeaderMatcher, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch.prototype.clearHeadersList = function() {
  this.setHeadersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.repeatedFields_ = [4];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.ClusterSpecifierCase = {
  CLUSTER_SPECIFIER_NOT_SET: 0,
  CLUSTER: 1,
  WEIGHTED_CLUSTERS: 2
};

/**
 * @return {proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.ClusterSpecifierCase}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.getClusterSpecifierCase = function() {
  return /** @type {proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.ClusterSpecifierCase} */(jspb.Message.computeOneofCase(this, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    cluster: jspb.Message.getFieldWithDefault(msg, 1, ""),
    weightedClusters: (f = msg.getWeightedClusters()) && proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.toObject(includeInstance, f),
    metadataMatch: (f = msg.getMetadataMatch()) && envoy_api_v2_core_base_pb.Metadata.toObject(includeInstance, f),
    rateLimitsList: jspb.Message.toObjectList(msg.getRateLimitsList(),
    envoy_api_v2_route_route_pb.RateLimit.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction;
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCluster(value);
      break;
    case 2:
      var value = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster;
      reader.readMessage(value,proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.deserializeBinaryFromReader);
      msg.setWeightedClusters(value);
      break;
    case 3:
      var value = new envoy_api_v2_core_base_pb.Metadata;
      reader.readMessage(value,envoy_api_v2_core_base_pb.Metadata.deserializeBinaryFromReader);
      msg.setMetadataMatch(value);
      break;
    case 4:
      var value = new envoy_api_v2_route_route_pb.RateLimit;
      reader.readMessage(value,envoy_api_v2_route_route_pb.RateLimit.deserializeBinaryFromReader);
      msg.addRateLimits(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWeightedClusters();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.serializeBinaryToWriter
    );
  }
  f = message.getMetadataMatch();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      envoy_api_v2_core_base_pb.Metadata.serializeBinaryToWriter
    );
  }
  f = message.getRateLimitsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      envoy_api_v2_route_route_pb.RateLimit.serializeBinaryToWriter
    );
  }
};


/**
 * optional string cluster = 1;
 * @return {string}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.getCluster = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.setCluster = function(value) {
  jspb.Message.setOneofField(this, 1, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.clearCluster = function() {
  jspb.Message.setOneofField(this, 1, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.hasCluster = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional WeightedCluster weighted_clusters = 2;
 * @return {?proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.getWeightedClusters = function() {
  return /** @type{?proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster, 2));
};


/** @param {?proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster|undefined} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.setWeightedClusters = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.clearWeightedClusters = function() {
  this.setWeightedClusters(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.hasWeightedClusters = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional envoy.api.v2.core.Metadata metadata_match = 3;
 * @return {?proto.envoy.api.v2.core.Metadata}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.getMetadataMatch = function() {
  return /** @type{?proto.envoy.api.v2.core.Metadata} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_base_pb.Metadata, 3));
};


/** @param {?proto.envoy.api.v2.core.Metadata|undefined} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.setMetadataMatch = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.clearMetadataMatch = function() {
  this.setMetadataMatch(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.hasMetadataMatch = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated envoy.api.v2.route.RateLimit rate_limits = 4;
 * @return {!Array<!proto.envoy.api.v2.route.RateLimit>}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.getRateLimitsList = function() {
  return /** @type{!Array<!proto.envoy.api.v2.route.RateLimit>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_api_v2_route_route_pb.RateLimit, 4));
};


/** @param {!Array<!proto.envoy.api.v2.route.RateLimit>} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.setRateLimitsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.envoy.api.v2.route.RateLimit=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.api.v2.route.RateLimit}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.addRateLimits = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.envoy.api.v2.route.RateLimit, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction.prototype.clearRateLimitsList = function() {
  this.setRateLimitsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.toObject = function(includeInstance, msg) {
  var f, obj = {
    clustersList: jspb.Message.toObjectList(msg.getClustersList(),
    proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster;
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight;
      reader.readMessage(value,proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.deserializeBinaryFromReader);
      msg.addClusters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClustersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    weight: (f = msg.getWeight()) && google_protobuf_wrappers_pb.UInt32Value.toObject(includeInstance, f),
    metadataMatch: (f = msg.getMetadataMatch()) && envoy_api_v2_core_base_pb.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight;
  return proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.UInt32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt32Value.deserializeBinaryFromReader);
      msg.setWeight(value);
      break;
    case 3:
      var value = new envoy_api_v2_core_base_pb.Metadata;
      reader.readMessage(value,envoy_api_v2_core_base_pb.Metadata.deserializeBinaryFromReader);
      msg.setMetadataMatch(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWeight();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.UInt32Value.serializeBinaryToWriter
    );
  }
  f = message.getMetadataMatch();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      envoy_api_v2_core_base_pb.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.UInt32Value weight = 2;
 * @return {?proto.google.protobuf.UInt32Value}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.getWeight = function() {
  return /** @type{?proto.google.protobuf.UInt32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt32Value, 2));
};


/** @param {?proto.google.protobuf.UInt32Value|undefined} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.setWeight = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.clearWeight = function() {
  this.setWeight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.hasWeight = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional envoy.api.v2.core.Metadata metadata_match = 3;
 * @return {?proto.envoy.api.v2.core.Metadata}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.getMetadataMatch = function() {
  return /** @type{?proto.envoy.api.v2.core.Metadata} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_base_pb.Metadata, 3));
};


/** @param {?proto.envoy.api.v2.core.Metadata|undefined} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.setMetadataMatch = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.clearMetadataMatch = function() {
  this.setMetadataMatch(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.prototype.hasMetadataMatch = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated ClusterWeight clusters = 1;
 * @return {!Array<!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight>}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.prototype.getClustersList = function() {
  return /** @type{!Array<!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight, 1));
};


/** @param {!Array<!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight>} value */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.prototype.setClustersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight}
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.prototype.addClusters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.prototype.clearClustersList = function() {
  this.setClustersList([]);
};


goog.object.extend(exports, proto.envoy.config.filter.network.thrift_proxy.v2alpha1);
