/* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var envoy_api_v2_route_route_pb = require('./envoy/api/v2/route/route_pb.js');
goog.object.extend(proto, envoy_api_v2_route_route_pb);
var envoy_type_percent_pb = require('./envoy/type/percent_pb.js');
goog.object.extend(proto, envoy_type_percent_pb);
var validate_validate_pb = require('./validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
var gogoproto_gogo_pb = require('./gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.envoy.config.filter.http.health_check.v2.HealthCheck', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.http.health_check.v2.HealthCheck.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.filter.http.health_check.v2.HealthCheck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.health_check.v2.HealthCheck.displayName = 'proto.envoy.config.filter.http.health_check.v2.HealthCheck';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.health_check.v2.HealthCheck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.health_check.v2.HealthCheck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.toObject = function(includeInstance, msg) {
  var f, obj = {
    passThroughMode: (f = msg.getPassThroughMode()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    cacheTime: (f = msg.getCacheTime()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    clusterMinHealthyPercentagesMap: (f = msg.getClusterMinHealthyPercentagesMap()) ? f.toObject(includeInstance, proto.envoy.type.Percent.toObject) : [],
    headersList: jspb.Message.toObjectList(msg.getHeadersList(),
    envoy_api_v2_route_route_pb.HeaderMatcher.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.health_check.v2.HealthCheck}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.health_check.v2.HealthCheck;
  return proto.envoy.config.filter.http.health_check.v2.HealthCheck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.health_check.v2.HealthCheck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.health_check.v2.HealthCheck}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setPassThroughMode(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setCacheTime(value);
      break;
    case 4:
      var value = msg.getClusterMinHealthyPercentagesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.envoy.type.Percent.deserializeBinaryFromReader, "");
         });
      break;
    case 5:
      var value = new envoy_api_v2_route_route_pb.HeaderMatcher;
      reader.readMessage(value,envoy_api_v2_route_route_pb.HeaderMatcher.deserializeBinaryFromReader);
      msg.addHeaders(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.health_check.v2.HealthCheck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.health_check.v2.HealthCheck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPassThroughMode();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getCacheTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getClusterMinHealthyPercentagesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.envoy.type.Percent.serializeBinaryToWriter);
  }
  f = message.getHeadersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      envoy_api_v2_route_route_pb.HeaderMatcher.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.BoolValue pass_through_mode = 1;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.getPassThroughMode = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 1));
};


/** @param {?proto.google.protobuf.BoolValue|undefined} value */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.setPassThroughMode = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.clearPassThroughMode = function() {
  this.setPassThroughMode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.hasPassThroughMode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Duration cache_time = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.getCacheTime = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.setCacheTime = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.clearCacheTime = function() {
  this.setCacheTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.hasCacheTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * map<string, envoy.type.Percent> cluster_min_healthy_percentages = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.envoy.type.Percent>}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.getClusterMinHealthyPercentagesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.envoy.type.Percent>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.envoy.type.Percent));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.clearClusterMinHealthyPercentagesMap = function() {
  this.getClusterMinHealthyPercentagesMap().clear();
};


/**
 * repeated envoy.api.v2.route.HeaderMatcher headers = 5;
 * @return {!Array<!proto.envoy.api.v2.route.HeaderMatcher>}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.getHeadersList = function() {
  return /** @type{!Array<!proto.envoy.api.v2.route.HeaderMatcher>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_api_v2_route_route_pb.HeaderMatcher, 5));
};


/** @param {!Array<!proto.envoy.api.v2.route.HeaderMatcher>} value */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.setHeadersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.envoy.api.v2.route.HeaderMatcher=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.api.v2.route.HeaderMatcher}
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.addHeaders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.envoy.api.v2.route.HeaderMatcher, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.health_check.v2.HealthCheck.prototype.clearHeadersList = function() {
  this.setHeadersList([]);
};


goog.object.extend(exports, proto.envoy.config.filter.http.health_check.v2);
