/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var validate_validate_pb = require('./validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
goog.exportSymbol('proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.repeatedFields_, proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.oneofGroups_);
};
goog.inherits(proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.displayName = 'proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.displayName = 'proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.repeatedFields_ = [2,6];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.oneofGroups_ = [[1,4]];

/**
 * @enum {number}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.DescriptorSetCase = {
  DESCRIPTOR_SET_NOT_SET: 0,
  PROTO_DESCRIPTOR: 1,
  PROTO_DESCRIPTOR_BIN: 4
};

/**
 * @return {proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.DescriptorSetCase}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getDescriptorSetCase = function() {
  return /** @type {proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.DescriptorSetCase} */(jspb.Message.computeOneofCase(this, proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.toObject = function(includeInstance, msg) {
  var f, obj = {
    protoDescriptor: jspb.Message.getFieldWithDefault(msg, 1, ""),
    protoDescriptorBin: msg.getProtoDescriptorBin_asB64(),
    servicesList: jspb.Message.getRepeatedField(msg, 2),
    printOptions: (f = msg.getPrintOptions()) && proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.toObject(includeInstance, f),
    matchIncomingRequestRoute: jspb.Message.getFieldWithDefault(msg, 5, false),
    ignoredQueryParametersList: jspb.Message.getRepeatedField(msg, 6),
    autoMapping: jspb.Message.getFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder;
  return proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProtoDescriptor(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setProtoDescriptorBin(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addServices(value);
      break;
    case 3:
      var value = new proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions;
      reader.readMessage(value,proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.deserializeBinaryFromReader);
      msg.setPrintOptions(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMatchIncomingRequestRoute(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addIgnoredQueryParameters(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoMapping(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getServicesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getPrintOptions();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.serializeBinaryToWriter
    );
  }
  f = message.getMatchIncomingRequestRoute();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getIgnoredQueryParametersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getAutoMapping();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    addWhitespace: jspb.Message.getFieldWithDefault(msg, 1, false),
    alwaysPrintPrimitiveFields: jspb.Message.getFieldWithDefault(msg, 2, false),
    alwaysPrintEnumsAsInts: jspb.Message.getFieldWithDefault(msg, 3, false),
    preserveProtoFieldNames: jspb.Message.getFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions;
  return proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAddWhitespace(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAlwaysPrintPrimitiveFields(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAlwaysPrintEnumsAsInts(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPreserveProtoFieldNames(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddWhitespace();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getAlwaysPrintPrimitiveFields();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getAlwaysPrintEnumsAsInts();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getPreserveProtoFieldNames();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional bool add_whitespace = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.getAddWhitespace = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.setAddWhitespace = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool always_print_primitive_fields = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.getAlwaysPrintPrimitiveFields = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.setAlwaysPrintPrimitiveFields = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool always_print_enums_as_ints = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.getAlwaysPrintEnumsAsInts = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.setAlwaysPrintEnumsAsInts = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool preserve_proto_field_names = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.getPreserveProtoFieldNames = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions.prototype.setPreserveProtoFieldNames = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string proto_descriptor = 1;
 * @return {string}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getProtoDescriptor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.setProtoDescriptor = function(value) {
  jspb.Message.setOneofField(this, 1, proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.clearProtoDescriptor = function() {
  jspb.Message.setOneofField(this, 1, proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.hasProtoDescriptor = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes proto_descriptor_bin = 4;
 * @return {string}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getProtoDescriptorBin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes proto_descriptor_bin = 4;
 * This is a type-conversion wrapper around `getProtoDescriptorBin()`
 * @return {string}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getProtoDescriptorBin_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getProtoDescriptorBin()));
};


/**
 * optional bytes proto_descriptor_bin = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getProtoDescriptorBin()`
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getProtoDescriptorBin_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getProtoDescriptorBin()));
};


/** @param {!(string|Uint8Array)} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.setProtoDescriptorBin = function(value) {
  jspb.Message.setOneofField(this, 4, proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.clearProtoDescriptorBin = function() {
  jspb.Message.setOneofField(this, 4, proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.hasProtoDescriptorBin = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string services = 2;
 * @return {!Array<string>}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getServicesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.setServicesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.addServices = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.clearServicesList = function() {
  this.setServicesList([]);
};


/**
 * optional PrintOptions print_options = 3;
 * @return {?proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getPrintOptions = function() {
  return /** @type{?proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions, 3));
};


/** @param {?proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions|undefined} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.setPrintOptions = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.clearPrintOptions = function() {
  this.setPrintOptions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.hasPrintOptions = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool match_incoming_request_route = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getMatchIncomingRequestRoute = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.setMatchIncomingRequestRoute = function(value) {
  jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * repeated string ignored_query_parameters = 6;
 * @return {!Array<string>}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getIgnoredQueryParametersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/** @param {!Array<string>} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.setIgnoredQueryParametersList = function(value) {
  jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.addIgnoredQueryParameters = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.clearIgnoredQueryParametersList = function() {
  this.setIgnoredQueryParametersList([]);
};


/**
 * optional bool auto_mapping = 7;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.getAutoMapping = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 7, false));
};


/** @param {boolean} value */
proto.envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.prototype.setAutoMapping = function(value) {
  jspb.Message.setProto3BooleanField(this, 7, value);
};


goog.object.extend(exports, proto.envoy.config.filter.http.transcoder.v2);
