/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_api_v2_core_address_pb = require('./envoy/api/v2/core/address_pb.js');
goog.object.extend(proto, envoy_api_v2_core_address_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var validate_validate_pb = require('./validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
var gogoproto_gogo_pb = require('./gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.displayName = 'proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.toObject = function(includeInstance, msg) {
  var f, obj = {
    authApiCluster: jspb.Message.getFieldWithDefault(msg, 1, ""),
    statPrefix: jspb.Message.getFieldWithDefault(msg, 2, ""),
    refreshDelay: (f = msg.getRefreshDelay()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    ipWhiteListList: jspb.Message.toObjectList(msg.getIpWhiteListList(),
    envoy_api_v2_core_address_pb.CidrRange.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth;
  return proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthApiCluster(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatPrefix(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRefreshDelay(value);
      break;
    case 4:
      var value = new envoy_api_v2_core_address_pb.CidrRange;
      reader.readMessage(value,envoy_api_v2_core_address_pb.CidrRange.deserializeBinaryFromReader);
      msg.addIpWhiteList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthApiCluster();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatPrefix();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRefreshDelay();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getIpWhiteListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      envoy_api_v2_core_address_pb.CidrRange.serializeBinaryToWriter
    );
  }
};


/**
 * optional string auth_api_cluster = 1;
 * @return {string}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.getAuthApiCluster = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.setAuthApiCluster = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stat_prefix = 2;
 * @return {string}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.getStatPrefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.setStatPrefix = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Duration refresh_delay = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.getRefreshDelay = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.setRefreshDelay = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.clearRefreshDelay = function() {
  this.setRefreshDelay(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.hasRefreshDelay = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated envoy.api.v2.core.CidrRange ip_white_list = 4;
 * @return {!Array<!proto.envoy.api.v2.core.CidrRange>}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.getIpWhiteListList = function() {
  return /** @type{!Array<!proto.envoy.api.v2.core.CidrRange>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_api_v2_core_address_pb.CidrRange, 4));
};


/** @param {!Array<!proto.envoy.api.v2.core.CidrRange>} value */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.setIpWhiteListList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.envoy.api.v2.core.CidrRange=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.api.v2.core.CidrRange}
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.addIpWhiteList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.envoy.api.v2.core.CidrRange, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth.prototype.clearIpWhiteListList = function() {
  this.setIpWhiteListList([]);
};


goog.object.extend(exports, proto.envoy.config.filter.network.client_ssl_auth.v2);
