/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_config_filter_network_dubbo_proxy_v2alpha1_route_pb = require('./envoy/config/filter/network/dubbo_proxy/v2alpha1/route_pb.js');
goog.object.extend(proto, envoy_config_filter_network_dubbo_proxy_v2alpha1_route_pb);
var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var validate_validate_pb = require('./validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
var gogoproto_gogo_pb = require('./gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter', null, global);
goog.exportSymbol('proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy', null, global);
goog.exportSymbol('proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType', null, global);
goog.exportSymbol('proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.displayName = 'proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.displayName = 'proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.toObject = function(includeInstance, msg) {
  var f, obj = {
    statPrefix: jspb.Message.getFieldWithDefault(msg, 1, ""),
    protocolType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    serializationType: jspb.Message.getFieldWithDefault(msg, 3, 0),
    routeConfigList: jspb.Message.toObjectList(msg.getRouteConfigList(),
    envoy_config_filter_network_dubbo_proxy_v2alpha1_route_pb.RouteConfiguration.toObject, includeInstance),
    dubboFiltersList: jspb.Message.toObjectList(msg.getDubboFiltersList(),
    proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy;
  return proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatPrefix(value);
      break;
    case 2:
      var value = /** @type {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType} */ (reader.readEnum());
      msg.setProtocolType(value);
      break;
    case 3:
      var value = /** @type {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType} */ (reader.readEnum());
      msg.setSerializationType(value);
      break;
    case 4:
      var value = new envoy_config_filter_network_dubbo_proxy_v2alpha1_route_pb.RouteConfiguration;
      reader.readMessage(value,envoy_config_filter_network_dubbo_proxy_v2alpha1_route_pb.RouteConfiguration.deserializeBinaryFromReader);
      msg.addRouteConfig(value);
      break;
    case 5:
      var value = new proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter;
      reader.readMessage(value,proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.deserializeBinaryFromReader);
      msg.addDubboFilters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatPrefix();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProtocolType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getSerializationType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getRouteConfigList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      envoy_config_filter_network_dubbo_proxy_v2alpha1_route_pb.RouteConfiguration.serializeBinaryToWriter
    );
  }
  f = message.getDubboFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.serializeBinaryToWriter
    );
  }
};


/**
 * optional string stat_prefix = 1;
 * @return {string}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.getStatPrefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.setStatPrefix = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ProtocolType protocol_type = 2;
 * @return {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.getProtocolType = function() {
  return /** @type {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType} value */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.setProtocolType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional SerializationType serialization_type = 3;
 * @return {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.getSerializationType = function() {
  return /** @type {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType} value */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.setSerializationType = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * repeated RouteConfiguration route_config = 4;
 * @return {!Array<!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.RouteConfiguration>}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.getRouteConfigList = function() {
  return /** @type{!Array<!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.RouteConfiguration>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_config_filter_network_dubbo_proxy_v2alpha1_route_pb.RouteConfiguration, 4));
};


/** @param {!Array<!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.RouteConfiguration>} value */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.setRouteConfigList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.RouteConfiguration=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.RouteConfiguration}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.addRouteConfig = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.RouteConfiguration, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.clearRouteConfigList = function() {
  this.setRouteConfigList([]);
};


/**
 * repeated DubboFilter dubbo_filters = 5;
 * @return {!Array<!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter>}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.getDubboFiltersList = function() {
  return /** @type{!Array<!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter, 5));
};


/** @param {!Array<!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter>} value */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.setDubboFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.addDubboFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.prototype.clearDubboFiltersList = function() {
  this.setDubboFiltersList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    config: (f = msg.getConfig()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter;
  return proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Any config = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.prototype.getConfig = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 2));
};


/** @param {?proto.google.protobuf.Any|undefined} value */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.prototype.setConfig = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.prototype.clearConfig = function() {
  this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * @enum {number}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType = {
  DUBBO: 0
};

/**
 * @enum {number}
 */
proto.envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType = {
  HESSIAN2: 0
};

goog.object.extend(exports, proto.envoy.config.filter.network.dubbo_proxy.v2alpha1);
