/* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_api_v2_core_base_pb = require('./envoy/api/v2/core/base_pb.js');
goog.object.extend(proto, envoy_api_v2_core_base_pb);
var envoy_api_v2_core_http_uri_pb = require('./envoy/api/v2/core/http_uri_pb.js');
goog.object.extend(proto, envoy_api_v2_core_http_uri_pb);
var envoy_api_v2_route_route_pb = require('./envoy/api/v2/route/route_pb.js');
goog.object.extend(proto, envoy_api_v2_route_route_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var validate_validate_pb = require('./validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
var gogoproto_gogo_pb = require('./gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks', null, global);
goog.exportSymbol('proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.repeatedFields_, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.oneofGroups_);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.oneofGroups_);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.displayName = 'proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.repeatedFields_ = [2,6,7];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.JwksSourceSpecifierCase = {
  JWKS_SOURCE_SPECIFIER_NOT_SET: 0,
  REMOTE_JWKS: 3,
  LOCAL_JWKS: 4
};

/**
 * @return {proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.JwksSourceSpecifierCase}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getJwksSourceSpecifierCase = function() {
  return /** @type {proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.JwksSourceSpecifierCase} */(jspb.Message.computeOneofCase(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuer: jspb.Message.getFieldWithDefault(msg, 1, ""),
    audiencesList: jspb.Message.getRepeatedField(msg, 2),
    remoteJwks: (f = msg.getRemoteJwks()) && proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.toObject(includeInstance, f),
    localJwks: (f = msg.getLocalJwks()) && envoy_api_v2_core_base_pb.DataSource.toObject(includeInstance, f),
    forward: jspb.Message.getFieldWithDefault(msg, 5, false),
    fromHeadersList: jspb.Message.toObjectList(msg.getFromHeadersList(),
    proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.toObject, includeInstance),
    fromParamsList: jspb.Message.getRepeatedField(msg, 7),
    forwardPayloadHeader: jspb.Message.getFieldWithDefault(msg, 8, ""),
    payloadInMetadata: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIssuer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addAudiences(value);
      break;
    case 3:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.deserializeBinaryFromReader);
      msg.setRemoteJwks(value);
      break;
    case 4:
      var value = new envoy_api_v2_core_base_pb.DataSource;
      reader.readMessage(value,envoy_api_v2_core_base_pb.DataSource.deserializeBinaryFromReader);
      msg.setLocalJwks(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setForward(value);
      break;
    case 6:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.deserializeBinaryFromReader);
      msg.addFromHeaders(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addFromParams(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setForwardPayloadHeader(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPayloadInMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuer();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAudiencesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getRemoteJwks();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.serializeBinaryToWriter
    );
  }
  f = message.getLocalJwks();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      envoy_api_v2_core_base_pb.DataSource.serializeBinaryToWriter
    );
  }
  f = message.getForward();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getFromHeadersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.serializeBinaryToWriter
    );
  }
  f = message.getFromParamsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getForwardPayloadHeader();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getPayloadInMetadata();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string issuer = 1;
 * @return {string}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getIssuer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.setIssuer = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string audiences = 2;
 * @return {!Array<string>}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getAudiencesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.setAudiencesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.addAudiences = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.clearAudiencesList = function() {
  this.setAudiencesList([]);
};


/**
 * optional RemoteJwks remote_jwks = 3;
 * @return {?proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getRemoteJwks = function() {
  return /** @type{?proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks, 3));
};


/** @param {?proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.setRemoteJwks = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.clearRemoteJwks = function() {
  this.setRemoteJwks(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.hasRemoteJwks = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional envoy.api.v2.core.DataSource local_jwks = 4;
 * @return {?proto.envoy.api.v2.core.DataSource}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getLocalJwks = function() {
  return /** @type{?proto.envoy.api.v2.core.DataSource} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_base_pb.DataSource, 4));
};


/** @param {?proto.envoy.api.v2.core.DataSource|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.setLocalJwks = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.clearLocalJwks = function() {
  this.setLocalJwks(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.hasLocalJwks = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool forward = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getForward = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.setForward = function(value) {
  jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * repeated JwtHeader from_headers = 6;
 * @return {!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader>}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getFromHeadersList = function() {
  return /** @type{!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader, 6));
};


/** @param {!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader>} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.setFromHeadersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.addFromHeaders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.clearFromHeadersList = function() {
  this.setFromHeadersList([]);
};


/**
 * repeated string from_params = 7;
 * @return {!Array<string>}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getFromParamsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<string>} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.setFromParamsList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.addFromParams = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.clearFromParamsList = function() {
  this.setFromParamsList([]);
};


/**
 * optional string forward_payload_header = 8;
 * @return {string}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getForwardPayloadHeader = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.setForwardPayloadHeader = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string payload_in_metadata = 9;
 * @return {string}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.getPayloadInMetadata = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.prototype.setPayloadInMetadata = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.toObject = function(includeInstance, msg) {
  var f, obj = {
    httpUri: (f = msg.getHttpUri()) && envoy_api_v2_core_http_uri_pb.HttpUri.toObject(includeInstance, f),
    cacheDuration: (f = msg.getCacheDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_api_v2_core_http_uri_pb.HttpUri;
      reader.readMessage(value,envoy_api_v2_core_http_uri_pb.HttpUri.deserializeBinaryFromReader);
      msg.setHttpUri(value);
      break;
    case 2:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setCacheDuration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHttpUri();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_api_v2_core_http_uri_pb.HttpUri.serializeBinaryToWriter
    );
  }
  f = message.getCacheDuration();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional envoy.api.v2.core.HttpUri http_uri = 1;
 * @return {?proto.envoy.api.v2.core.HttpUri}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.getHttpUri = function() {
  return /** @type{?proto.envoy.api.v2.core.HttpUri} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_http_uri_pb.HttpUri, 1));
};


/** @param {?proto.envoy.api.v2.core.HttpUri|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.setHttpUri = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.clearHttpUri = function() {
  this.setHttpUri(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.hasHttpUri = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Duration cache_duration = 2;
 * @return {?proto.google.protobuf.Duration}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.getCacheDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 2));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.setCacheDuration = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.clearCacheDuration = function() {
  this.setCacheDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RemoteJwks.prototype.hasCacheDuration = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    valuePrefix: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValuePrefix(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValuePrefix();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value_prefix = 2;
 * @return {string}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.prototype.getValuePrefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtHeader.prototype.setValuePrefix = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.toObject = function(includeInstance, msg) {
  var f, obj = {
    providerName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    audiencesList: jspb.Message.getRepeatedField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProviderName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addAudiences(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProviderName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAudiencesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional string provider_name = 1;
 * @return {string}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.prototype.getProviderName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.prototype.setProviderName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string audiences = 2;
 * @return {!Array<string>}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.prototype.getAudiencesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.prototype.setAudiencesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.prototype.addAudiences = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.prototype.clearAudiencesList = function() {
  this.setAudiencesList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.oneofGroups_ = [[1,2,3,4,5]];

/**
 * @enum {number}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.RequiresTypeCase = {
  REQUIRES_TYPE_NOT_SET: 0,
  PROVIDER_NAME: 1,
  PROVIDER_AND_AUDIENCES: 2,
  REQUIRES_ANY: 3,
  REQUIRES_ALL: 4,
  ALLOW_MISSING_OR_FAILED: 5
};

/**
 * @return {proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.RequiresTypeCase}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.getRequiresTypeCase = function() {
  return /** @type {proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.RequiresTypeCase} */(jspb.Message.computeOneofCase(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.toObject = function(includeInstance, msg) {
  var f, obj = {
    providerName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    providerAndAudiences: (f = msg.getProviderAndAudiences()) && proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.toObject(includeInstance, f),
    requiresAny: (f = msg.getRequiresAny()) && proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.toObject(includeInstance, f),
    requiresAll: (f = msg.getRequiresAll()) && proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.toObject(includeInstance, f),
    allowMissingOrFailed: (f = msg.getAllowMissingOrFailed()) && google_protobuf_empty_pb.Empty.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProviderName(value);
      break;
    case 2:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.deserializeBinaryFromReader);
      msg.setProviderAndAudiences(value);
      break;
    case 3:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.deserializeBinaryFromReader);
      msg.setRequiresAny(value);
      break;
    case 4:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.deserializeBinaryFromReader);
      msg.setRequiresAll(value);
      break;
    case 5:
      var value = new google_protobuf_empty_pb.Empty;
      reader.readMessage(value,google_protobuf_empty_pb.Empty.deserializeBinaryFromReader);
      msg.setAllowMissingOrFailed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProviderAndAudiences();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences.serializeBinaryToWriter
    );
  }
  f = message.getRequiresAny();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.serializeBinaryToWriter
    );
  }
  f = message.getRequiresAll();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.serializeBinaryToWriter
    );
  }
  f = message.getAllowMissingOrFailed();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_empty_pb.Empty.serializeBinaryToWriter
    );
  }
};


/**
 * optional string provider_name = 1;
 * @return {string}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.getProviderName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.setProviderName = function(value) {
  jspb.Message.setOneofField(this, 1, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.clearProviderName = function() {
  jspb.Message.setOneofField(this, 1, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.hasProviderName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ProviderWithAudiences provider_and_audiences = 2;
 * @return {?proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.getProviderAndAudiences = function() {
  return /** @type{?proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences, 2));
};


/** @param {?proto.envoy.config.filter.http.jwt_authn.v2alpha.ProviderWithAudiences|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.setProviderAndAudiences = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.clearProviderAndAudiences = function() {
  this.setProviderAndAudiences(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.hasProviderAndAudiences = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional JwtRequirementOrList requires_any = 3;
 * @return {?proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.getRequiresAny = function() {
  return /** @type{?proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList, 3));
};


/** @param {?proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.setRequiresAny = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.clearRequiresAny = function() {
  this.setRequiresAny(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.hasRequiresAny = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional JwtRequirementAndList requires_all = 4;
 * @return {?proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.getRequiresAll = function() {
  return /** @type{?proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList, 4));
};


/** @param {?proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.setRequiresAll = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.clearRequiresAll = function() {
  this.setRequiresAll(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.hasRequiresAll = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Empty allow_missing_or_failed = 5;
 * @return {?proto.google.protobuf.Empty}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.getAllowMissingOrFailed = function() {
  return /** @type{?proto.google.protobuf.Empty} */ (
    jspb.Message.getWrapperField(this, google_protobuf_empty_pb.Empty, 5));
};


/** @param {?proto.google.protobuf.Empty|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.setAllowMissingOrFailed = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.clearAllowMissingOrFailed = function() {
  this.setAllowMissingOrFailed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.prototype.hasAllowMissingOrFailed = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.toObject = function(includeInstance, msg) {
  var f, obj = {
    requirementsList: jspb.Message.toObjectList(msg.getRequirementsList(),
    proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.deserializeBinaryFromReader);
      msg.addRequirements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequirementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.serializeBinaryToWriter
    );
  }
};


/**
 * repeated JwtRequirement requirements = 1;
 * @return {!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement>}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.prototype.getRequirementsList = function() {
  return /** @type{!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement, 1));
};


/** @param {!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement>} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.prototype.setRequirementsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.prototype.addRequirements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementOrList.prototype.clearRequirementsList = function() {
  this.setRequirementsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.toObject = function(includeInstance, msg) {
  var f, obj = {
    requirementsList: jspb.Message.toObjectList(msg.getRequirementsList(),
    proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.deserializeBinaryFromReader);
      msg.addRequirements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequirementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.serializeBinaryToWriter
    );
  }
};


/**
 * repeated JwtRequirement requirements = 1;
 * @return {!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement>}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.prototype.getRequirementsList = function() {
  return /** @type{!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement, 1));
};


/** @param {!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement>} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.prototype.setRequirementsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.prototype.addRequirements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirementAndList.prototype.clearRequirementsList = function() {
  this.setRequirementsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.toObject = function(includeInstance, msg) {
  var f, obj = {
    match: (f = msg.getMatch()) && envoy_api_v2_route_route_pb.RouteMatch.toObject(includeInstance, f),
    requires: (f = msg.getRequires()) && proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_api_v2_route_route_pb.RouteMatch;
      reader.readMessage(value,envoy_api_v2_route_route_pb.RouteMatch.deserializeBinaryFromReader);
      msg.setMatch(value);
      break;
    case 2:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.deserializeBinaryFromReader);
      msg.setRequires(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMatch();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_api_v2_route_route_pb.RouteMatch.serializeBinaryToWriter
    );
  }
  f = message.getRequires();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.serializeBinaryToWriter
    );
  }
};


/**
 * optional envoy.api.v2.route.RouteMatch match = 1;
 * @return {?proto.envoy.api.v2.route.RouteMatch}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.getMatch = function() {
  return /** @type{?proto.envoy.api.v2.route.RouteMatch} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_route_route_pb.RouteMatch, 1));
};


/** @param {?proto.envoy.api.v2.route.RouteMatch|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.setMatch = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.clearMatch = function() {
  this.setMatch(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.hasMatch = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional JwtRequirement requires = 2;
 * @return {?proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.getRequires = function() {
  return /** @type{?proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement, 2));
};


/** @param {?proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.setRequires = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.clearRequires = function() {
  this.setRequires(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.prototype.hasRequires = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    requiresMap: (f = msg.getRequiresMap()) ? f.toObject(includeInstance, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = msg.getRequiresMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRequiresMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement.serializeBinaryToWriter);
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<string, JwtRequirement> requires = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement>}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.prototype.getRequiresMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtRequirement));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.prototype.clearRequiresMap = function() {
  this.getRequiresMap().clear();
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.toObject = function(includeInstance, msg) {
  var f, obj = {
    providersMap: (f = msg.getProvidersMap()) ? f.toObject(includeInstance, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.toObject) : [],
    rulesList: jspb.Message.toObjectList(msg.getRulesList(),
    proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.toObject, includeInstance),
    filterStateRules: (f = msg.getFilterStateRules()) && proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication;
  return proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getProvidersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.deserializeBinaryFromReader, "");
         });
      break;
    case 2:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.deserializeBinaryFromReader);
      msg.addRules(value);
      break;
    case 3:
      var value = new proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule;
      reader.readMessage(value,proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.deserializeBinaryFromReader);
      msg.setFilterStateRules(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProvidersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider.serializeBinaryToWriter);
  }
  f = message.getRulesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule.serializeBinaryToWriter
    );
  }
  f = message.getFilterStateRules();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule.serializeBinaryToWriter
    );
  }
};


/**
 * map<string, JwtProvider> providers = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider>}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.getProvidersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtProvider));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.clearProvidersMap = function() {
  this.getProvidersMap().clear();
};


/**
 * repeated RequirementRule rules = 2;
 * @return {!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule>}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.getRulesList = function() {
  return /** @type{!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule, 2));
};


/** @param {!Array<!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule>} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.setRulesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.addRules = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.envoy.config.filter.http.jwt_authn.v2alpha.RequirementRule, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.clearRulesList = function() {
  this.setRulesList([]);
};


/**
 * optional FilterStateRule filter_state_rules = 3;
 * @return {?proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.getFilterStateRules = function() {
  return /** @type{?proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule, 3));
};


/** @param {?proto.envoy.config.filter.http.jwt_authn.v2alpha.FilterStateRule|undefined} value */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.setFilterStateRules = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.clearFilterStateRules = function() {
  this.setFilterStateRules(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication.prototype.hasFilterStateRules = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.envoy.config.filter.http.jwt_authn.v2alpha);
